log_url_template: http://logs.tungsten.io/periodic-nightly/review.opencontrail.org/{}/{}/
gitlog_path: zuul-info/gitlog.builder.md
new_inventory: False
gerrit_host: https://review.opencontrail.org
verify_gerrit_ssl: True
fetch_repos: True
git_dir: /tmp/build_changes
job_list:
    - build-variables-init
    - contrail-build-vro-plugin
    - contrail-go-docker
    - contrail-vnc-build-containers-centos7-newton
    - contrail-vnc-build-containers-centos7-ocata
    - contrail-vnc-build-containers-centos7-queens
    - contrail-vnc-build-containers-rhel7-ocata
    - contrail-vnc-build-containers-rhel7-queens
    - contrail-vnc-build-package-centos74
    - contrail-vnc-build-package-rhel7-ocata
    - contrail-vnc-build-package-rhel7-queens
    - contrail-vnc-build-test-containers
    - contrail-vnc-publish-containers-nightly
    - post-nightly-registry-port
    - publish-dev-env
job_blacklist:
    - build-variables-init
    - post-nightly-registry-port
